# Generated by Django 5.2.9 on 2026-01-20 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, db_table='articles_article_likes', related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
